version: 2

models:
  - name: used_cars_business_metrics
    description: >
      Business metrics by car year and make.
      columns:
      - name: price_retention
        description: Sum of the the car price accross all years and make.
        tests:
            - not_null:
                severity: error
      - name: mileage_utilization
        description: Sum of the the car mileage accross all years and make.
        tests:
            - not_null:
                severity: error
  - name: used_cars_inventory
    description: >
      Used car inventory corresponding to both countries (USA and Canada).